server:
  port: 8765

spring:
  application:
    name: api-gateway-service
  sleuth:
    sampler:
      probability: 1.0


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
