server:
  port: 8100
  servlet:
    context-path: /currency-conversion

spring:
  application:
    name: currency-conversion-service
  config:
    import: optional:configserver:http://localhost:8888
  sleuth:
    sampler:
      probability: 1.0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
