server:
  port: 8000
  servlet:
    context-path: /currency-exchange

spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: currency-exchange-service
  jpa:
    show-sql: true
    defer-datasource-initialization: true
  datasource:
    url: jdbc:h2:mem:testDb
  h2:
    console:
      enabled: true
  sleuth:
    sampler:
      probability: 1.0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

resilience4j:
  retry:
    instances:
      retry-number:
        maxRetryAttempts: 5